apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  strategy: { }
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - image: ghcr.io/elliotwms/emojistats:$APP_VERSION
          name: $APP_NAME
          resources: { }
          env:
            - name: APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME
                  key: APPLICATION_ID
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME
                  key: TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME
                  key: DATABASE_URL
            - name: HEALTH_CHECK_ADDR
              value: ":8080"
---
apiVersion: v1
data:
  APPLICATION_ID: $EMOJISTATS_APPLICATION_ID
  TOKEN: $EMOJISTATS_TOKEN
  DATABASE_URL: $EMOJISTATS_DATABASE_URL
kind: Secret
metadata:
  name: $APP_NAME
