name: Deploy
on:
  release:
    types: [ released ]
jobs:
  deploy:
    strategy:
      matrix:
        environment: [Test]
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    env:
      APP_NAME: ${{ vars.EMOJISTATS_APPLICATION_NAME }}
      APP_VERSION: ${{ github.ref_name }}
      EMOJISTATS_APPLICATION_ID: ${{ secrets.EMOJISTATS_APPLICATION_ID }}
      EMOJISTATS_TOKEN: ${{ secrets.EMOJISTATS_TOKEN }}
      EMOJISTATS_DATABASE_URL: ${{ secrets.EMOJISTATS_DATABASE_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Update deployment file
      run: envsubst < $GITHUB_WORKSPACE/.github/workflows/deploy/emojistats-deployment.yml >> $GITHUB_WORKSPACE/deployment.yml
    - name: Verify deployment
      run: cat $GITHUB_WORKSPACE/deployment.yml
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/deployment.yml
    - name: Verify deployment
      run: kubectl rollout status deployment/${{ vars.EMOJISTATS_APPLICATION_NAME }}
